package com.shruglabs.shrug;

import com.shruglabs.shrug.client.ShrugClient;
import com.shruglabs.shrug.server.ShrugServer;
import com.sun.istack.internal.Nullable;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SeqSEE' at '8/30/16 1:09 AM' with Gradle 2.9
 *
 * @author SeqSEE, @date 8/30/16 1:09 AM
 */
public class Shrug {

	private ShrugServer server;
	private ShrugClient client;
	public static  Shrug shrug; 
	
	public static void main(String[] args){
		shrug = new Shrug();
		shrug.startClient(null);
		
		
		
		
		
		
	}
	
    public void startServer(@Nullable String args) {
    	if(args == null){
		System.out.println("shrug$ Initializing Integrated Server");
    	shrug.setServer(new ShrugServer());
    	shrug.getServer().setPort(37756);
		System.out.println("shrug$ Done!");
    	}
	}

	public boolean startClient(@Nullable String args) {
		if(args != null && args.equals("test")){
			shrug.setClient(new ShrugClient());
			Thread t = new Thread(shrug.getClient());
			t.run();
			t.interrupt();
			return true;
		}
		else{
			shrug.setClient(new ShrugClient());
			Thread t = new Thread(shrug.getClient());
			t.run();
			return false;
		}
		
		
	}

	/*
	private static void startServer(@Nullable String args) {
		shrug.setServer(new ShrugServer());
		new Thread(shrug.getServer()).start();
		
	}
	*/

	private void setClient(ShrugClient shrugClient) {
		// TODO Auto-generated method stub
		
	}

	public ShrugServer getServer() {
		return shrug.server;
	}

	public void setServer(ShrugServer server) {
		shrug.server = server;
	}

	public ShrugClient getClient() {
		return shrug.client;
	}





}
