/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarah' at '9/2/16 7:25 PM' with Gradle 2.9
 *
 * @author Sarah, @date 9/2/16 7:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
